### PR TITLE
update and remove the "www" files bundled

### PR DESCRIPTION
**Pull request by michaeloffner**
i made them more specific for docker

Screenshot 2024-06-05 at 14 44 15
Screenshot 2024-06-05 at 14 45 26

### CODE REVIEW

**Comment by zspitzer** [comment]
Looking nice, is there a link to the Admin?

**Comment by isapir** [comment]
Are all these extensions installed by default? Can we make some of them optional? Many users don't use any of them, especially in a lean environment like Docker

**Comment by zspitzer** [comment]
We've already unbundled a lot of extensions in 6.0, what else do you want to chop? For lean and mean you start with light (or zero) and add your desired choices.

**Comment by michaeloffner** [comment]
@zspitzer yes

**Pull request merged**
